<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>CinemaSeatReservationWithFSharp</RootNamespace>
  </PropertyGroup>
	<ItemGroup>
		<None Include="newupdates.sql" />

		<Compile Include="Password.fs" />
		<Compile Include="Db.fs" />

		<None Include="init.sql">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<Content Include="appsettings.json">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>

		<!-- Models -->
		<Compile Include="Models\User.fs" />
		<Compile Include="Models\Role.fs" />
		<Compile Include="Models\Seat.fs" />
		<Compile Include="Models\Hall.fs" />
		<Compile Include="Models\Movie.fs" />
		<Compile Include="Models\Screening.fs" />

		<!-- Repositories -->
		<Compile Include="Repositories\UserRepo.fs" />
		<Compile Include="Repositories\SeatDto.fs" />
		<Compile Include="Repositories\SeatRepository.fs" />
		<Compile Include="Repositories\HallsRepo.fs" />
		<Compile Include="Repositories\MovieRepo.fs" />
		<Compile Include="Repositories\ScreeningRepo.fs" />

		<!-- Services -->
		<Compile Include="Services\UserService.fs" />
		<Compile Include="Services\SeatService.fs" />
		<Compile Include="Services\HallService.fs" />
		<Compile Include="Services\MoviesService.fs" />
		<Compile Include="Services\ScreeningService.fs" />
		<Compile Include="Services\TicketService.fs" />

		<!-- Program -->
		<Compile Include="Program.fs" />
	</ItemGroup>




	<ItemGroup>
    <PackageReference Include="Dapper" Version="2.1.66" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="6.1.3" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="10.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" Version="10.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="10.0.0" />
  </ItemGroup>
	
	
	
	
	
	
	

</Project>
